MD \VOL002\ACSGL
MD \VOL002\GLMSTR
CD \
PAUSE INSERT GENERAL LEDGER PROGRAM DISKETTE #1 IN DRIVE A:
COPY A:*.* \VOL002\ACSGL
PAUSE INSERT GENERAL LEDGER PROGRAM DISKETTE #2 IN DRIVE A:
COPY A:*.* \VOL002\ACSGL
PAUSE INSERT GENERAL LEDGER PROGRAM DISKETTE #3 IN DRIVE A:
COPY A:*.* \VOL002\ACSGL
PAUSE INSERT GENERAL LEDGER MASTER FILE DISKETTE IN DRIVE A:
COPY A:*.* \VOL002\GLMSTR
ACSMENU
MD \VOL002\ACSAP
MD \VOL002\APMSTR
CD \
PAUSE INSERT ACCOUNTS PAYABLE  PROGRAM DISKETTE #1 IN DRIVE A:
COPY A:*.* \VOL002\ACSAP
PAUSE INSERT ACCOUNTS PAYABLE PROGRAM DISKETTE #2 IN DRIVE A:
COPY A:*.* \VOL002\ACSAP
PAUSE INSERT ACCOUNTS PAYABLE MASTER FILE  DISKETTE IN DRIVE A:
COPY A:*.* \VOL002\APMSTR
ACSMENU
MD \VOL002\ACSPR
MD \VOL002\PRMSTR
CD \
PAUSE INSERT PAYROLL  PROGRAM DISKETTE #1 IN DRIVE A:
COPY A:*.* \VOL002\ACSPR
PAUSE INSERT PAYROLL  PROGRAM DISKETTE #2 IN DRIVE A:
COPY A:*.* \VOL002\ACSPR
PAUSE INSERT PAYROLL PROGRAM DISKETTE #3 IN DRIVE A:
COPY A:*.* \VOL002\ACSPR
PAUSE INSERT PAYROLL MASTER FILE DISKETTE IN DRIVE A:
COPY A:*.* \VOL002\PRMSTR
ACSMENU
