! consider adding clean up fntos calls
! consider adding clean up fnacs to fnacs2 calls
! consider adding clean up fnXit capitalization
! consider adding clean up Xit capitalization
! consider adding clean up fnTop capitalization
! consider adding clean up include: Ertn capitalization
autoLibrary
on error goto Ertn
fntop(program$)
tab$=chr$(9)
fn_getList
fileCount=udim(mat fileName$)
countlinesRemoved=countAutoLibraryAdded=countLineCount= _
	countLibraryOfferingProgram=countProgramWithLineNumbers=0
for item=1 to fileCount
	fnStatus(str$(item)&'/'&str$(fileCount)&': '&fileName$(item))
	! fnStatusPause
	open #hIn :=fnGetHandle: 'name='&fileName$(item),d,i
	dim tmpFile$*512
	tmpFile$=env$('temp')&'\acs\tmpSourceFile.br.brs'
	open #hOut:=fnGetHandle: 'name='&tmpFile$&',RecL=1024,Replace',d,o
	encounteredAutoLibrary=lineCount=enableSkipThisFile=0
	do
		dim line$*2048
		linput #hIn: line$ eof EoIn
		dim ln$*2048 ! modified version of line$ for testing purposes
		dim tab$*1
		tab$=chr$(9)
		tabLevel=fn_tabLevel(line$)

		ln$=srep$(line$,tab$,'')
		ln$=trim$(ln$)
		fn_stripComment(ln$)
		lineCount+=1
		if lineCount=1 then
			lineVal=val(ln$(1:5)) conv ignore
		en if
		if lineVal then
			fnStatus('file has line numbers - skipping it.')
			countProgramWithLineNumbers+=1
			enableSkipThisFile=1
			goto EoIn
		else if ln$(1:11)='autolibrary' then
			encounteredAutoLibrary=1
			pr #hOut: line$
		else if ln$(1:14)='def library fn' and ln$(15:15)<>'_' then
			countLibraryOfferingProgram+=1
			fnStatus('program offers a library lets just skip these for now and see how many they are')
			enableSkipThisFile=1
			goto EoIn
		else if ln$(1:6)='def fn' and ln$(7:7)<>'_' then
			encounterBadFn=1
			fnStatus('Illegally named function: '&ln$)
			execute 'sy ""C:\ACS\Program\Notepad++\notepad++.exe" "'&filename$(item)&'" -n'&str$(lineCount)&'"'
			! pause
			fnStatusPause
			enableSkipThisFile=1
			goto EoIn
		else if ln$(1:11)="library 'S:\Core\Libary':" and ~encounteredAutoLibrary then
			encounteredAutoLibrary=1
			pr #hOut: rpt$(tab$,tablevel)&'autoLibrary'
			countAutoLibraryAdded+=1
		else if ln$(1:11)="library 'S:\Core\Libary':" and encounteredAutoLibrary then
			! not even a blank line ! pr #hOut: ''
			countlinesRemoved+=1
		else
			fn_acsToAcs2(line$)
			pr #hOut: line$
		end if
	loop
	EoIn: !
	close #hIn:
	close #hOut:
	countLineCount+=lineCount
	if ~enableSkipThisFile then
		! fnCopy(tmpFile$,fileName$(item))
	end if
nex item
! r: Totals Screen
fnStatus('files processed: '&str$(item))
fnStatus('lines processed: '&str$(countLineCount))
fnStatus('lines removed: '&str$(countlinesRemoved))
fnStatus('autoLibrary added: '&str$(countAutoLibraryAdded))
fnStatus('Library Offering Programs (skipped): '&str$(countLibraryOfferingProgram))
fnStatus('Programs with Line Numbers (skipped): '&str$(countProgramWithLineNumbers))
fnStatusPause
! /r
end
Xit: fnXit
def fn_tabLevel(&line$; ___,it,returnN)
	it=5 ! highest tested for level
	do until returnN or ~it
		it-=1
		if line$(1:(it))=rpt$(tab$,it) then 
			returnN=it
		end if
	loop 
	fn_tabLevel=returnN
fnend
def fn_stripComment(&ln$; ___,ePos)
	ePos=pos(ln$,'!')
	if ePos>0 then
		ln$(ePos:inf)=''
	en if
fnend
def fn_lineContains
	fn_lineContains=1
fnend
def fn_getList
	dim fileName$(0)*512
	mat fileName$(0)
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\agedap.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\bank.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\bankreconciliation.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\chartofaccounts.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\checkalloc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\chgbank.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\cklstv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\apmstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\fntrmstr_v0_to_v1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\fundmstr-recl75.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\glbld-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\glmstr-to-recl62.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\payalloc-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\paymstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\paymstr-v0-to-v1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\paymstr2-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\paymstr9-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\paytrans-v1-to-v2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\tralloc-v1-to-v2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\trmstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\trmstr-v1-to-v2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\trmstr2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\Conversion\unpdaloc-v1-to-v2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\cpinvlst.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\department.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\dptmstr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\dueby.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\endorsment.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\fixalloc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\fnbankbal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\fnreceipt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\fnupdatebankbal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\glcontrol.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\initglcoa.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\initglpay.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\paidinvoice.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\paydump.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\paylist.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\paymentcode.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\payzero.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\printselectinvoice.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\receipt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\removepaidinvoices.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\renumck.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\reorgunpaid.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\rmtrans.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\tralloc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\transactionhamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\trjr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\trtocpa.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\unclbank.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\unpaidinvoice.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\unpaidinvoicehamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsCL\vnfund.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\account_search.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglauto.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglbalf.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglbld.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglblds.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglblds_lib.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglcas5.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglcasb.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglcasf.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglcash.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglcaso.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglchg.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglchgc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglchgr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglchgs.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglchrt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglclr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglcovl.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acgldet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglinc4p.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglinc6b.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincb.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincb6.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincf.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglinco.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincq.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglinct.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglincy.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglinyy.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglmrge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglnote.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglrest.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglrev.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglschp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acglwksh.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acprcks_hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acprscr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\acprscr_lib.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\actpd$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\actpd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\actrans.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\actrans_change_glnumber.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\addcno.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\adjustaccounts.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\asciiglm.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\autoproc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\bankrec.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\bankreconciliation.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\bargraph.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\bgmaint2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\bldfin.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\bldrange.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\bld_d_records.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\budinpt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\budwksh.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\cch$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\clbld.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\cmbbud.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\combgl.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\acglbld.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\acglcovl-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\acglnote-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\acglrest-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\actrans-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\add-h.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\add_missing.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\cnvmstr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\fns-fix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\fns4-fix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\gl-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\gl2-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\glall-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\glbld109-fix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\glmstr-338-416.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\glmstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\glpayee_v0_to_v1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\gltrans-fix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\incref-fix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\prmstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Conversion\reass.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\coverletterprint.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\dumppayeetrans.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\elec1099.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\employee_search.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fix gltrans - delete by date.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fixbal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fixref.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fixytdqtd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\Fix_AcPRCks_Dates.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fnacglblds.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fnacprscr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fnactpd$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fnactpd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fncch$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fnglfs.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fnglmerge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fnsfm.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\fundbal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\glbrecon.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\glckrec.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\glelecw2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\gljcmrge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\glmstr_hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\glreass.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\gltrans.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\glzer109.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\otherdeductions.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\otherdeductionsytd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\payeetype.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\payroll.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\pr941.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\prclose.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\prelecuc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\prmerge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\prmstr_hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\prstatuc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\prtexasuc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\przqtd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\przytd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\ratio.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\reverse.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\schedule_hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\texasuc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\transcodes.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\unpost.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\vendorreas.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\vendortranslist.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\w2box16.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\w2SuplimentalHamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\year.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsGL\yearendtb.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\adjustpaydate.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\category_srch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\cat_srch2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\chartofaccounts.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\cmbcat.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\cmbcategory.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\cmbemp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\cmbjob.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\cmbsubcat.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\ckhist-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\cnvall-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\crckhist-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\fixmedicare.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\fundmstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\jcmstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\paymstr-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\prall-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\prckhist-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\prckhist-fix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\prgl-fix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\v4_cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\Conversion\v4_part2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\employee_srch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\fix_ss_med_wages.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\hourclassification.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\hourclassification2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\hours.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\hours_lib.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcbldscr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcinptc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcipbil.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcmerge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcnamlst.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcpctcmp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt20.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt3.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt4.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt5.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt6.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt7.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprnt8.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcprtdet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcremove.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcrpt-mod.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcrptfm.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcrpts1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jcstwksh.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\jczcur.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\job_srch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newautoproc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcipbil.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcmaint.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcmerge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcmrgc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcnamlst.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcpctcmp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcprnt1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcprtdet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcremove.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcrpt-mod.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcrptfm.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcrpts1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjcstwksh.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newjczcur.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newmglmstr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newpr941.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newprauto.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newprreg2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newprrpt3.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newprrpt4.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newprrpts1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newprusrdr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\newqtrfeduc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\prelecuc.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\prrpt2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\prrpt4.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\prusrdr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\prw2b.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\pulllay.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\removechecks.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\rpwork01_hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\ss_emp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\subcat_srch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\subcmbcat.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\timecard.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsPR\YTD Wage Breakdown.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\argldist.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\arinput.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\arinput_import_csv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\arprtbil.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\artb.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\artrans.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\client.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\clilabel.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\clilpt2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\csv2tm.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\emaint.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\emremter.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\emzercur.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\ivdmaint.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\print_invoice.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\support.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\Support2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\svmaint.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmclidir.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmclilst.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmcofm.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tminpinv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tminput.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmmobsum.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmmrginp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmmrginv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmmrgman.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmsclist.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmsearch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmsrvprd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmstafdr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmtrans.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmunagpt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsTM\tmzytd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\averagesewer.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\avgchg.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\avgsewchg.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\balbrkfix.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\billingrpt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\billrpt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\budrpt1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\calk_chatom.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\calk_standard.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\chartofaccounts.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\checkbalbrk.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\check_balance_breakdowns.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\cmbact.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\assign_sequence.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\bld_trans.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\bld_trans_std.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\booktitle.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\booktitle_altbil.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\collection.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\csz-wipe-altbil.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\csz-wipe.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\fixfinalbilling.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\fixroutes.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\note-cnv-c7.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\note-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\remove_blank_altadr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\ubadrbil-cnv.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Conversion\ubmstr-vb.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\customer_hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\depreas.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\duplicate_customer_report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\duptr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ECP_Export.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\escrow1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Export_IMSB.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\eyegraph.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\Fix - Recreate Transaction File.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\fix_use_alt_billing_addr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\meter location delete selected.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\meter location fix selected.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\postgl.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\PrintBill_Moweaqua.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\pulllay.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ratelist.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\redate.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\remove_excessive_balance.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\reset_readings.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\totalbal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\typeofservices.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubacctr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubanlyze.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubbargraph.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubbudlst.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubcass1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubcass2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubcass_convert.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubcoldel.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubcoldt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubdelinq.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubnotes.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubowed.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubpdreminder.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprt3prace_granby.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_bethany.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_chatom.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_div.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_fin.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_gra.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_kin.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_ll.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_millry.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_purdy.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_scottville.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_thayer.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_tho.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtbl1_wh.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtfull_ashgrove.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtlas_cerro.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtprace_ash.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubprtthree_brier.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubrevcal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\ubrevcaldouble.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\usagedol.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\acsUB\workOrderHamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\BR Order Entry\Company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Claims or Purchases Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Fix\Correct Transaction Statment Cleared Dates.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Payee Labels.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Payee.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Print 1099 Forms.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Print Checks.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Running Bank Balance.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Transaction.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Unpaid Invoice Listing (Current).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Unpaid Invoice Summary.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Checkbook\Unpaid Invoice.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\Company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\cpt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\Finan Records Purge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\fn\claimFolder.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\fn\messageBox.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\Move Folder Contents into Claim Attachment Folders.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\test\fnSpecialFolderPath.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Collection-Master Add-On\test\internal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Ace\fnShortPath.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Ace\GetCD.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Ace\Win3B.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ACS_Component.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\AddCNo.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Check File Versions.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Client.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\CmbCNo.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\CNo.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Company Import.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Confirm.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\copy.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\CReg_Hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\dec2hex.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\email.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Favorites.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\File Open and Save.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\askFileName.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\chain.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\error.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\getDir2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\makeSurePathExists.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\top.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\wait.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\windowsStart.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fn\xit.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fnagl$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fnbutton_or_disabled.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fnFixWordingOnGrid.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fnMsgBox.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fnrgl$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fnSnap\fnMsExe.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\fnSnap\rtflib_dll.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\gridlayout.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\HamsterFio.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\hamster_print.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\hamster_setup.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\hex2dec.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\inch2twip.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Index.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ini.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Label\fnaddlabel.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Label\fnlabel.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\locate.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\locate2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Menu.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\oldmsgbox.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\osver.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Parse\csz.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Parse\remove2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Print\w2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Print\w3.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Print.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\print1099.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\PrintAce.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\PrintPdf.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\process.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\1099.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\1099box.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\1099Type.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\About.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\amortiz.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\br2brs.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\brs2br.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\Client Server.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\eye.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\flexdir.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\Preferences.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\PrintAce_Setup.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\PrintAce_Test.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\printlay1.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\printlay2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\printtest.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\race.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\Select Company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\state.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\Update.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Programs\web.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\program_properties.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\PrtFlex\gridlayout.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\PrtFlex\Grids.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\PrtFlex\prtflex2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\PrtFlex\pulllay.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\reg.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\reg_hamster.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\Function\co_properties_btn_ok.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\Function\co_properties_enter.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\Function\co_w2_margins_enter.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\Function\defaults\enter.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\screenio\MeterAddressSelect.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\screenio\Properties.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\screenio\StateCombo.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\screenio\StateEdit.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\screenio\StateList.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\screenio\Test.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\ScreenIO\screenio\W-2Margins.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\search.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\serviceCamp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\specialFolderPath.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\Start.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\status.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\twip2inch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Core\xit.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\barcode.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\clmstr2support.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\cv_remover.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\make_source.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\Notepad++ CallTip Refresh.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\prb.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\xmldiff.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Dev\xmldiff.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Accountants\Employee.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Accountants\Print Payroll Registers.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Accounts.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Balance Sheet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Close Books at Year End.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Close Month.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Comparative Balance Sheet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Enter Standard Adjustments.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Enter Transactions.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Financial Statement Design.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Fix Current Balance.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Fix Period Accumulators from History.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Four Column Budget Income Statement.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Income Statement.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Payee.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Period Comparison Balance Sheet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Post Standard Adjustments.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Print 1099 Forms.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Print Accumulated Trial Balance.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Print Schedules.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Print W-2 Forms.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Prior Period Adjustments.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Schedule.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Test Balance Sheet Design.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\General Ledger\Trial Balance.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Active Employee List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Annual Federal Unemployment Worksheet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Change Payroll Dates.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Corrected Electronic W-2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Deferred Compensation Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Direct Deposit List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Direct Deposits.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Electronic 401K.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Electronic W-2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Employee Departments.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Employee Review Register.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Enter Time Sheets.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1009).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1018).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1020).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1021).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1029).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1040).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1048).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1072).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1078).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1082).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV (client 3393 cno 1092).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Import Transactions from CSV.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Fix\Update Checkbook from Check History.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\fn\dedNames.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\fn\deptName.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Import Time from Time Clock System.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Input Worksheet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Category.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Certified Payroll Register (Part 2).br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Certified Payroll Register.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Corrected W-2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Enter (Job Cost) Time.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Enter Charges.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\fnBurden_srch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\fnCmbBurden.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Personnel Burden.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Job Cost\Sub-Category Description.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Labels.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Other Pay and Deductions Register.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Payroll Check History.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Payroll Registers.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Payroll Tax Deposit Summary.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Pension Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Post to General Ledger.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Print 1099 Forms.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Print Payroll Checks.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Print W-2 Forms.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Reverse Calculation.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\State UnEmp Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\Workmans Compensation Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\YTD and QTD Register.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Payroll\YTD Deductions Register.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\2000.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\applicantsearch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\button.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\cd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\check.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\cmbact.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\cmbcno.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\comboa.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\combof.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\console.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\csz.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\cursys.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\customersearch.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\datepicker.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\error.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\finetransaction.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\flex.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnautomatedsavepoint.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fncm_filename$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fncombof.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fncustomer_address.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fngetcd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fngetpp.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnHamsterFio.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnmsexe.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnOpenFile.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnopenreceiptprinter.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnPicBut.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnProgressBar.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnsafe_filename$.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnshortpath.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fnSystemNameFromAbbr.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\fntxt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\frame.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\free.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\getcd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\getdir.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\getlpd.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\gl balance sheet.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\gld.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\glnumber.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\grid.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\label3.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\Montys Doors.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\msgbox.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\msgbox2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\multiline.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\pause.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\paytransaction.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\pic.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\print1099.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\SpoolPath.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\tab.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\test_msgbox.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\txt.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\txtdisable.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\TEST\wait.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\ACS Invoices.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\Category.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\Collections.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\Delete Transaction.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\Email Queued Invoices.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\Enter and Print Invoices.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\fn\customerHasEbilling.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\fn\printInvoice.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\fn\reassignNTA.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\Import CSV to Time Sheets.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Time Management\Update support expiration date.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Add An Other Charge.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Additional Penalty Calculation.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Annual Usage Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Billing Journal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Calculate Bills.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Calculate Sewer Average.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Cash Receipts Journal.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Change Wrong Billing Date.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Collections.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Company.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Consumption List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Create Bank Draft File.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Customer.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Deposit Change List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Deposit List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Display Last Date Customer File Accessed.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Enter Beginning Balances and Readings.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Export and Import Route and Sequence.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Export Billing Addresses by Rate Code.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Export UB Master File.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Fix\Customer Routes and Rate Codes.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Fix\Multiply Current and Prior Readings.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Fix\Multiply Sequence Numbers by 10.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Fix\Swap Current and Prior Readings.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Fix\Transactions Missing After Upgrade from ACS 4.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\fn\calculateBills.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\fn\cmbRt2.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\fn\eftData.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\fn\lastBillingDate.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Forgot to Zero Year-To-Date.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Hand Held\Create Hand Held File.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Hand Held\Fix\Remove Meter Locations without Service Ids.br - Copy.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Hand Held\Fix\Set All Meter Locations to Type N.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Hand Held\Import CSV to Meter Location.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Hand Held\Meter Address.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Hand Held\Meter Information.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Hand Held\Meter Location.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Labels.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Name and Number List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Past Due and Turn Off List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Penalty Calculation.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Per 1000 Usage.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Rate Analysis.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Rates.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Recalculate All Current Bills.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Remove Old Budget Transactions.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Reverse Billing Cycle.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Reverse Calculation.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Transaction Listing.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Transactions.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Transfer Accounts Between Companies.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Type of Service.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Unbilled Customer Listing.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Undo Penalty Calculation.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Usage Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Work Order Add.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Work Order List.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Work Order Print.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Zero Usage Report.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\Utility Billing\Zero Year to Date Usage.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\WORK\printlay.br.brs')
	fnAddOneC(mat fileName$,'C:\ACS\Dev-5\WORK\signature.br.brs')
fnend
def fn_acsToAcs2(&line$; ___,posX,removing$*12,adding$*7)
	removing$='fnacs(sn$,0,' ! must be lwrc$
	adding$='fnAcs2('
	removingLen=len(removing$)
	posX=pos(lwrc$(line$),removing$)
	if posX>0 then
		pr 'before line$: '&line$
		line$(posX:posX+removingLen)=adding$
		pr ' after line$: '&line$
		pause
	end if
fnend
include: Ertn
